/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/Layouts/components/Content/index.vue')['default']
    Footer: typeof import('./src/components/Layouts/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Layouts/components/Header/index.vue')['default']
    Layouts: typeof import('./src/components/Layouts/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layouts/components/Sidebar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
